# Site
title:              The Thinking Rock
bio:                Hi, I'm William Qin
description:        "I'm here to share my opinions, personal thoughts, side projects, video games, and new ideas."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:year/:month/:title"
    layout: post
    author:

# Jekyll
permalink:          /:year/:month/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   default

# Analytics
analytics-id:       "UA-104496008-2"

# Social
facebook:           william.qin51
github:             WilliamLQin
linkedin:           williamqin
website:            williamqin.com
email:              hello@williamqin.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 9
paginate_path: "/page:num"

# jekyll-mentions:
#     base_url: https://twitter.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
